version: '2'

services:
  node:
    image: node:8-alpine
    working_dir: /usr/src/app
    network_mode: bridge
    volumes:
      - "./app:/usr/src/app"
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
