---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    app: hello-world
    tier: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: hello-world
    tier: dataabase
